### ISSUE TITLE
configure Maven for the project

### ISSUE THREAD

**Issue by lukik45** [lukik45/PUT-SE-BuildingInfo#12]
### DoD
- [x] mark the code with proper version number ( repo's tag = version number, pom.xml)

**Comment by bujowskis** [comment]
Unfortunately, there seem to be some problems with Surefire and Javadoc generation plugins, resulting in `mvn site` not working. I already searched the web quite extensively and can't get to work and since it doesn't really affect the rest, I'm just going to leave the issue open for now until we fix it

**Comment by bujowskis** [comment]
since Surefire is not yet needed and I resolved Javadoc gen, Maven config is complete
