### ISSUE TITLE
Write the script to automatically build the application

### ISSUE THREAD

**Issue by lukik45** [lukik45/PUT-SE-BuildingInfo#13]
### DoD
- [x] automatic compilation (the same way as we did on labs)
- [x] distribution package creation (jar)

**Comment by bujowskis** [comment]
Although I set up the actions workflow *(on a separate branch)* and added the missing `distributionManagement` section, the workflow is still failing due to `403: no permission error`.

I've been reading about it and it may have something to do with no permission to write packages. And since packages may actually have something with the repository owners, @lukik45 need to look into that.

Worth reading:
https://github.community/t/403-error-on-container-registry-push-from-github-action/173071/13

**Comment by bujowskis** [comment]
since @lukik45 already corrected the workflow creating distr jar (accessible via README `process` link)
